name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: indchi2020/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./scratch3
      - uses: actions/checkout@v2
        with:
          repository: indchi2020/ml2scratch
          path: ./ml2scratch
      - uses: actions/checkout@v2
        with:
          repository: indchi2020/posenet2scratch
          path: ./posenet2scratch
      - uses: actions/checkout@v2
        with:
          repository: yokobond/scratch-microbit-more
          path: ./scratch-microbit-more
      - uses: actions/checkout@v2
        with:
          repository: indchi2020/tm2scratch
          path: ./tm2scratch
      - uses: actions/checkout@v2
        with:
          repository: indchi2020/handpose2scratch
          path: ./handpose2scratch
      - uses: actions/checkout@v2
        with:
          repository: indchi2020/facemesh2scratch
          path: ./facemesh2scratch
      - uses: actions/checkout@v2
        
     
        with:
          repository: indchi2020/speech2scratch
          path: ./speech2scratch
      - uses: actions/checkout@v2
        
      
      - run: sh ./speech2scratch/install.sh
      - run: sh ./handpose2scratch/install.sh
      - run: sh ./facemesh2scratch/install.sh
      - run: sh ./tm2scratch/install.sh
      - run: node ./install.js --gui=..
        working-directory: ./scratch-microbit-more
      - run: sh ./posenet2scratch/install.sh
      - run: sh ./ml2scratch/install.sh
      - run: sh ./scratch3/add_ga_tracking_code.sh
      - run: npm run build
      - run: cp ./scratch3/index.html ./build/index.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
